// Mocks generated by Mockito 5.4.6 from annotations
// in vinas_mobile/test/features/biblioteca/ui/biblioteca_catalogo_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:ui' as _i9;

import 'package:dio/dio.dart' as _i7;
import 'package:image_picker/image_picker.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:vinas_mobile/core/api_client.dart' as _i8;
import 'package:vinas_mobile/core/models/prediction_model.dart' as _i12;
import 'package:vinas_mobile/features/auth/services/auth_service.dart' as _i2;
import 'package:vinas_mobile/features/biblioteca/services/biblioteca_service.dart'
    as _i5;
import 'package:vinas_mobile/features/coleccion/services/coleccion_service.dart'
    as _i4;
import 'package:vinas_mobile/features/foro/services/foro_service.dart' as _i3;
import 'package:vinas_mobile/features/perfil/services/perfil_service.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthService_0 extends _i1.SmartFake implements _i2.AuthService {
  _FakeAuthService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeForoService_1 extends _i1.SmartFake implements _i3.ForoService {
  _FakeForoService_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeColeccionService_2 extends _i1.SmartFake
    implements _i4.ColeccionService {
  _FakeColeccionService_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBibliotecaService_3 extends _i1.SmartFake
    implements _i5.BibliotecaService {
  _FakeBibliotecaService_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePerfilService_4 extends _i1.SmartFake implements _i6.PerfilService {
  _FakePerfilService_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDio_5 extends _i1.SmartFake implements _i7.Dio {
  _FakeDio_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i8.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthService get authDataSource => (super.noSuchMethod(
        Invocation.getter(#authDataSource),
        returnValue: _FakeAuthService_0(
          this,
          Invocation.getter(#authDataSource),
        ),
      ) as _i2.AuthService);

  @override
  _i3.ForoService get foroDataSource => (super.noSuchMethod(
        Invocation.getter(#foroDataSource),
        returnValue: _FakeForoService_1(
          this,
          Invocation.getter(#foroDataSource),
        ),
      ) as _i3.ForoService);

  @override
  _i4.ColeccionService get coleccionDataSource => (super.noSuchMethod(
        Invocation.getter(#coleccionDataSource),
        returnValue: _FakeColeccionService_2(
          this,
          Invocation.getter(#coleccionDataSource),
        ),
      ) as _i4.ColeccionService);

  @override
  _i5.BibliotecaService get bibliotecaDataSource => (super.noSuchMethod(
        Invocation.getter(#bibliotecaDataSource),
        returnValue: _FakeBibliotecaService_3(
          this,
          Invocation.getter(#bibliotecaDataSource),
        ),
      ) as _i5.BibliotecaService);

  @override
  _i6.PerfilService get perfilDataSource => (super.noSuchMethod(
        Invocation.getter(#perfilDataSource),
        returnValue: _FakePerfilService_4(
          this,
          Invocation.getter(#perfilDataSource),
        ),
      ) as _i6.PerfilService);

  @override
  _i7.Dio get dioInstance => (super.noSuchMethod(
        Invocation.getter(#dioInstance),
        returnValue: _FakeDio_5(
          this,
          Invocation.getter(#dioInstance),
        ),
      ) as _i7.Dio);

  @override
  set onTokenExpired(_i9.VoidCallback? value) => super.noSuchMethod(
        Invocation.setter(
          #onTokenExpired,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setToken(String? token) => super.noSuchMethod(
        Invocation.method(
          #setToken,
          [token],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<Map<String, dynamic>> ping() => (super.noSuchMethod(
        Invocation.method(
          #ping,
          [],
        ),
        returnValue:
            _i10.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<List<dynamic>> getPublicaciones() => (super.noSuchMethod(
        Invocation.method(
          #getPublicaciones,
          [],
        ),
        returnValue: _i10.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i10.Future<List<dynamic>>);

  @override
  _i10.Future<List<dynamic>> getUserPublicaciones() => (super.noSuchMethod(
        Invocation.method(
          #getUserPublicaciones,
          [],
        ),
        returnValue: _i10.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i10.Future<List<dynamic>>);

  @override
  _i10.Future<void> createPublicacion(
    String? titulo,
    String? texto, {
    _i11.XFile? imageFile,
    double? latitud,
    double? longitud,
    bool? esPublica = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPublicacion,
          [
            titulo,
            texto,
          ],
          {
            #imageFile: imageFile,
            #latitud: latitud,
            #longitud: longitud,
            #esPublica: esPublica,
          },
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> deletePublicacion(int? idPublicacion) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePublicacion,
          [idPublicacion],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<List<dynamic>> getComentariosPublicacion(int? idPublicacion) =>
      (super.noSuchMethod(
        Invocation.method(
          #getComentariosPublicacion,
          [idPublicacion],
        ),
        returnValue: _i10.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i10.Future<List<dynamic>>);

  @override
  _i10.Future<void> likePublicacion(int? idPublicacion) => (super.noSuchMethod(
        Invocation.method(
          #likePublicacion,
          [idPublicacion],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> unlikePublicacion(int? idPublicacion) =>
      (super.noSuchMethod(
        Invocation.method(
          #unlikePublicacion,
          [idPublicacion],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> likeComentario(int? idComentario) => (super.noSuchMethod(
        Invocation.method(
          #likeComentario,
          [idComentario],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> unlikeComentario(int? idComentario) => (super.noSuchMethod(
        Invocation.method(
          #unlikeComentario,
          [idComentario],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> createComentario(
    int? idPublicacion,
    String? texto, {
    int? idPadre,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createComentario,
          [
            idPublicacion,
            texto,
          ],
          {#idPadre: idPadre},
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> votarComentario(
    int? idComentario,
    bool? esLike,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #votarComentario,
          [
            idComentario,
            esLike,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> deleteComentario(int? idComentario) => (super.noSuchMethod(
        Invocation.method(
          #deleteComentario,
          [idComentario],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> saveToCollection({
    required _i11.XFile? imageFile,
    required String? nombreVariedad,
    String? notas,
    double? lat,
    double? lon,
    bool? esPublica = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveToCollection,
          [],
          {
            #imageFile: imageFile,
            #nombreVariedad: nombreVariedad,
            #notas: notas,
            #lat: lat,
            #lon: lon,
            #esPublica: esPublica,
          },
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<List<dynamic>> getCollection() => (super.noSuchMethod(
        Invocation.method(
          #getCollection,
          [],
        ),
        returnValue: _i10.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i10.Future<List<dynamic>>);

  @override
  _i10.Future<List<dynamic>> getUserCollection() => (super.noSuchMethod(
        Invocation.method(
          #getUserCollection,
          [],
        ),
        returnValue: _i10.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i10.Future<List<dynamic>>);

  @override
  _i10.Future<void> updateCollectionItem(
    int? idColeccion,
    Map<String, dynamic>? updates,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCollectionItem,
          [
            idColeccion,
            updates,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> deleteCollectionItem(int? idColeccion) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCollectionItem,
          [idColeccion],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<List<dynamic>> getColeccionesMapa({String? modo = 'publico'}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getColeccionesMapa,
          [],
          {#modo: modo},
        ),
        returnValue: _i10.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i10.Future<List<dynamic>>);

  @override
  _i10.Future<List<dynamic>> getVariedades() => (super.noSuchMethod(
        Invocation.method(
          #getVariedades,
          [],
        ),
        returnValue: _i10.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i10.Future<List<dynamic>>);

  @override
  _i10.Future<List<_i12.PredictionModel>> predictImage(_i11.XFile? file) =>
      (super.noSuchMethod(
        Invocation.method(
          #predictImage,
          [file],
        ),
        returnValue: _i10.Future<List<_i12.PredictionModel>>.value(
            <_i12.PredictionModel>[]),
      ) as _i10.Future<List<_i12.PredictionModel>>);

  @override
  _i10.Future<Map<String, dynamic>> getMe() => (super.noSuchMethod(
        Invocation.method(
          #getMe,
          [],
        ),
        returnValue:
            _i10.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<void> updateProfile(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [data],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> uploadAvatar(_i11.XFile? imageFile) => (super.noSuchMethod(
        Invocation.method(
          #uploadAvatar,
          [imageFile],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> toggleFavorite(int? idVariedad) => (super.noSuchMethod(
        Invocation.method(
          #toggleFavorite,
          [idVariedad],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<List<dynamic>> getFavorites() => (super.noSuchMethod(
        Invocation.method(
          #getFavorites,
          [],
        ),
        returnValue: _i10.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i10.Future<List<dynamic>>);

  @override
  _i10.Future<void> markTutorialAsComplete() => (super.noSuchMethod(
        Invocation.method(
          #markTutorialAsComplete,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}
