"""add variedad_sugerida

Revision ID: 16b0328b6044
Revises: 81012d914d39
Create Date: 2026-05-08 00:24:09.900312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16b0328b6044'
down_revision: Union[str, Sequence[str], None] = '81012d914d39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ValidacionesExperto', sa.Column('variedad_sugerida', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ValidacionesExperto', 'variedad_sugerida')
    # ### end Alembic commands ###
