"""Add AnotacionesImagenes table

Revision ID: 81012d914d39
Revises: e4b5c6d7e8f9
Create Date: 2026-05-07 19:55:06.669647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81012d914d39'
down_revision: Union[str, Sequence[str], None] = 'e4b5c6d7e8f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AnotacionesImagenes',
    sa.Column('id_anotacion', sa.Integer(), nullable=False),
    sa.Column('url_imagen', sa.String(length=512), nullable=False),
    sa.Column('es_buena', sa.Boolean(), nullable=False),
    sa.Column('id_validacion', sa.Integer(), nullable=False),
    sa.Column('id_variedad', sa.Integer(), nullable=False),
    sa.Column('fecha_anotacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_validacion'], ['ValidacionesExperto.id_validacion'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_variedad'], ['Variedades.id_variedad'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_anotacion')
    )
    op.create_index(op.f('ix_AnotacionesImagenes_id_anotacion'), 'AnotacionesImagenes', ['id_anotacion'], unique=False)
    op.drop_constraint(op.f('Comentarios_id_padre_fkey'), 'Comentarios', type_='foreignkey')
    op.create_foreign_key(None, 'Comentarios', 'Comentarios', ['id_padre'], ['id_comentario'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Comentarios', type_='foreignkey')
    op.create_foreign_key(op.f('Comentarios_id_padre_fkey'), 'Comentarios', 'Comentarios', ['id_padre'], ['id_comentario'], ondelete='CASCADE')
    op.drop_index(op.f('ix_AnotacionesImagenes_id_anotacion'), table_name='AnotacionesImagenes')
    op.drop_table('AnotacionesImagenes')
    # ### end Alembic commands ###
