"""Add expert validation module

Revision ID: e4b5c6d7e8f9
Revises: 0a0ae6034d6f
Create Date: 2026-05-07 17:50:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4b5c6d7e8f9'
down_revision: Union[str, Sequence[str], None] = 'd4a5c3cb051f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Usuarios', sa.Column('rol', sa.String(length=50), server_default='usuario', nullable=True))
    op.add_column('Usuarios', sa.Column('fcm_token', sa.String(length=255), nullable=True))
    op.add_column('Coleccion', sa.Column('solicita_validacion_experto', sa.Boolean(), server_default='false', nullable=True))
    
    op.create_table('ValidacionesExperto',
    sa.Column('id_validacion', sa.Integer(), nullable=False),
    sa.Column('id_coleccion', sa.Integer(), nullable=False),
    sa.Column('id_experto', sa.Integer(), nullable=True),
    sa.Column('solicitada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('validada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('es_correcta', sa.Boolean(), nullable=True),
    sa.Column('feedback_experto', sa.Text(), nullable=True),
    sa.Column('evaluacion_imagenes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_coleccion'], ['Coleccion.id_coleccion'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_experto'], ['Usuarios.id_usuario'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_validacion'),
    sa.UniqueConstraint('id_coleccion')
    )
    op.create_index(op.f('ix_ValidacionesExperto_id_validacion'), 'ValidacionesExperto', ['id_validacion'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ValidacionesExperto_id_validacion'), table_name='ValidacionesExperto')
    op.drop_table('ValidacionesExperto')
    op.drop_column('Coleccion', 'solicita_validacion_experto')
    op.drop_column('Usuarios', 'fcm_token')
    op.drop_column('Usuarios', 'rol')
    # ### end Alembic commands ###
